export const INITIAL_EMPLOYEES = [
  { id: 1, visa: 'DTH', firstName: 'Thien', lastName: 'Doan', birthDate: '1995-05-15' },
  { id: 2, visa: 'BHU', firstName: 'Hung', lastName: 'Bui', birthDate: '1992-08-20' },
  { id: 3, visa: 'JHV', firstName: 'Hai', lastName: 'Vu', birthDate: '1994-11-10' },
  { id: 4, visa: 'HTV', firstName: 'Thang', lastName: 'Vo', birthDate: '1990-03-25' },
  { id: 5, visa: 'NQN', firstName: 'Nhat', lastName: 'Nguyen', birthDate: '1996-07-12' },
  { id: 6, visa: 'HNH', firstName: 'Hao', lastName: 'Nguyen', birthDate: '1993-09-08' },
  { id: 7, visa: 'TQP', firstName: 'Phuong', lastName: 'Tran', birthDate: '1991-12-01' },
  { id: 8, visa: 'QMV', firstName: 'Minh', lastName: 'Quach', birthDate: '1989-04-18' },
  { id: 9, visa: 'FUN', firstName: 'Frank', lastName: 'Underwood', birthDate: '1985-03-30' },
  { id: 10, visa: 'KMA', firstName: 'Khoa', lastName: 'Mai', birthDate: '1993-07-22' },
  { id: 11, visa: 'TIN', firstName: 'Tin', lastName: 'Nguyen', birthDate: '1995-09-10' },
  { id: 12, visa: 'ATN', firstName: 'An', lastName: 'Tran', birthDate: '1991-04-18' },
  { id: 13, visa: 'HMT', firstName: 'Hoang', lastName: 'Minh', birthDate: '1987-08-14' },
  { id: 14, visa: 'GTN', firstName: 'Gia', lastName: 'Thinh', birthDate: '1994-02-28' },
];

export const INITIAL_GROUPS = [
  { id: 1, version: 0, groupLeader: { id: 1, version: 0, visa: 'DTH', firstName: 'Thien', lastName: 'Doan', birthDate: '1995-05-15' }, leaderVisa: 'DTH' },
  { id: 2, version: 0, groupLeader: { id: 2, version: 0, visa: 'BHU', firstName: 'Hung', lastName: 'Bui', birthDate: '1992-08-20' }, leaderVisa: 'BHU' },
  { id: 3, version: 0, groupLeader: { id: 3, version: 0, visa: 'JHV', firstName: 'Hai', lastName: 'Vu', birthDate: '1994-11-10' }, leaderVisa: 'JHV' },
  { id: 4, version: 0, groupLeader: { id: 5, version: 0, visa: 'NQN', firstName: 'Nhat', lastName: 'Nguyen', birthDate: '1996-07-12' }, leaderVisa: 'NQN' },
  { id: 5, version: 0, groupLeader: { id: 8, version: 0, visa: 'QMV', firstName: 'Minh', lastName: 'Quach', birthDate: '1989-04-18' }, leaderVisa: 'QMV' },
];

export const INITIAL_PROJECTS = [
  {
    id: 1,
    projectNumber: 3116,
    name: 'Facturation / Encaissements',
    customer: 'Les Retaites Populaires',
    groupId: 1,
    group: INITIAL_GROUPS[0],
    members: ['DTH', 'BHU'],
    employees: [INITIAL_EMPLOYEES[0], INITIAL_EMPLOYEES[1]],
    status: 'NEW',
    startDate: '2004-02-25',
    endDate: '2004-12-31',
    version: 1,
  },
  {
    id: 2,
    projectNumber: 3118,
    name: 'GKBWEB',
    customer: 'GKB',
    groupId: 2,
    group: INITIAL_GROUPS[1],
    members: ['JHV', 'FUN'],
    employees: [INITIAL_EMPLOYEES[2], INITIAL_EMPLOYEES[8]],
    status: 'FIN',
    startDate: '2002-10-10',
    endDate: '2003-08-15',
    version: 1,
  },
  {
    id: 3,
    projectNumber: 7157,
    name: 'MGBAHN-Maint2015',
    customer: 'MGB Tourism',
    groupId: 3,
    group: INITIAL_GROUPS[2],
    members: ['KMA', 'TIN'],
    employees: [INITIAL_EMPLOYEES[9], INITIAL_EMPLOYEES[10]],
    status: 'INP',
    startDate: '2006-09-24',
    endDate: '2007-06-30',
    version: 1,
  },
  {
    id: 4,
    projectNumber: 7174,
    name: 'SOMED-SPITEX MAINT',
    customer: 'SOMED-SPITEX MAINT',
    groupId: 4,
    group: INITIAL_GROUPS[3],
    members: ['DTH', 'ATN'],
    employees: [INITIAL_EMPLOYEES[0], INITIAL_EMPLOYEES[11]],
    status: 'NEW',
    startDate: '2015-10-05',
    endDate: '',
    version: 1,
  },
  {
    id: 5,
    projectNumber: 7199,
    name: 'ARCHIMEDE-2015-3.14',
    customer: 'Les Retaites Populaires',
    groupId: 1,
    group: INITIAL_GROUPS[0],
    members: ['JHV'],
    employees: [INITIAL_EMPLOYEES[2]],
    status: 'PLA',
    startDate: '2005-05-29',
    endDate: '2006-05-29',
    version: 1,
  },
  {
    id: 6,
    projectNumber: 8201,
    name: 'E-Banking Core Portal',
    customer: 'Credit Suisse',
    groupId: 5,
    group: INITIAL_GROUPS[4],
    members: ['GTN', 'HMT'],
    employees: [INITIAL_EMPLOYEES[13], INITIAL_EMPLOYEES[12]],
    status: 'NEW',
    startDate: '2018-03-01',
    endDate: '2019-01-15',
    version: 1,
  },
  {
    id: 7,
    projectNumber: 8205,
    name: 'Logistics Tracking System',
    customer: 'Swiss Post',
    groupId: 2,
    group: INITIAL_GROUPS[1],
    members: ['NQN', 'KMA'],
    employees: [INITIAL_EMPLOYEES[4], INITIAL_EMPLOYEES[9]],
    status: 'INP',
    startDate: '2019-06-15',
    endDate: '2020-12-31',
    version: 1,
  },
  {
    id: 8,
    projectNumber: 8210,
    name: 'Smart Metering Gateway',
    customer: 'Romande Energie',
    groupId: 3,
    group: INITIAL_GROUPS[2],
    members: ['FUN', 'TIN'],
    employees: [INITIAL_EMPLOYEES[8], INITIAL_EMPLOYEES[10]],
    status: 'PLA',
    startDate: '2020-01-10',
    endDate: '2021-06-30',
    version: 1,
  },
  {
    id: 9,
    projectNumber: 8215,
    name: 'Medical Claims Engine',
    customer: 'Groupe Mutuel',
    groupId: 4,
    group: INITIAL_GROUPS[3],
    members: ['DTH', 'BHU', 'JHV'],
    employees: [INITIAL_EMPLOYEES[0], INITIAL_EMPLOYEES[1], INITIAL_EMPLOYEES[2]],
    status: 'FIN',
    startDate: '2017-04-01',
    endDate: '2018-10-20',
    version: 1,
  },
  {
    id: 10,
    projectNumber: 1004,
    name: 'IOC CLIENT EXTRANET',
    customer: 'Customer C',
    groupId: 2,
    group: INITIAL_GROUPS[1],
    members: ['HTV', 'TQP', 'QMV'],
    employees: [INITIAL_EMPLOYEES[3], INITIAL_EMPLOYEES[6], INITIAL_EMPLOYEES[7]],
    status: 'FIN',
    startDate: '2023-01-01',
    endDate: '2024-01-01',
    version: 1,
  },
];
